// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brejchweqiuspprkjoef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZWpjaHdlcWl1c3Bwcmtqb2VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTE3MTYsImV4cCI6MjA2OTk2NzcxNn0.3hag-6PB5UxfZs2tdDHNKDYvaxLZJVKy1dbmJ0ZrVp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});