// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rhvwiyobordgxnbnfaqk.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJodndpeW9ib3JkZ3huYm5mYXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE1NDU0MTMsImV4cCI6MjA0NzEyMTQxM30.OgNkNwPDFaH9t1Kr3A1r5Y6LcKST2sbu-d0mF4E5BtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);